name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          user: FlorianBx
          token: ${{ secrets.METRICS_TOKEN }}
          #config_output: markdown
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
